### ISSUE TITLE
Add option to remove valid from field

### ISSUE THREAD

**Issue by yairsts** [utpal-barman/u-credit-card-flutter#14]
Hi, 
Currently the "valid from" text always appear, with or without value. 
I think maybe you should add option to hide this text at all. 

Thanks

**Comment by utpal-barman** [comment]
Hi @yairsts,

Thank you for bringing this to our attention! I'm happy to inform you that the issue has already been resolved in the latest version (1.1.0) of the `u_credit_card` package.

To update to the latest version, please add or update the package in your `pubspec.yaml` file as follows:

```yaml
dependencies:
  u_credit_card: ^1.1.0
  
```

After updating, you can now control the visibility of the "valid from" and "valid thru" sections using the showValidFrom and showValidThru parameters. Simply set them to false if you want to hide these sections.

Thank you for your feedback, and please feel free to reach out if you have any more questions or encounter any issues.

**Comment by yairsts** [comment]
Thank you. this is wonderful library.
