### ISSUE TITLE
Add option to flip the card

### ISSUE THREAD

**Issue by yairsts** [utpal-barman/u-credit-card-flutter#16]
Hi, 

Please add an option to flip the card back to show the CVV number. 
You can use flip_card library for this. 
 
Thank you :)

**Comment by utpal-barman** [comment]
Hi @yairsts 

Thank you for reaching out and suggesting an enhancement for the card-flipping feature. We've implemented your request, allowing users to flip the card back to reveal the CVV number.

This enhancement has been successfully resolved in pull request #19 on GitHub. You can expect version 1.2.0 to include this feature on pub.dev soon.
