### ISSUE TITLE
Adding flipcard causes an issue

### ISSUE THREAD

**Issue by Amein-Eskinder** [utpal-barman/u-credit-card-flutter#22]
<img width="492" alt="image" src="https://github.com/utpal-barman/u-credit-card-flutter/assets/62555273/0ad38edb-7994-4e31-9f27-899e8e49f257">
<img width="617" alt="image" src="https://github.com/utpal-barman/u-credit-card-flutter/assets/62555273/61f5e517-5fc4-482b-adda-341e750f39d8">
<img width="471" alt="image" src="https://github.com/utpal-barman/u-credit-card-flutter/assets/62555273/79d70241-deb2-4a60-84cd-91c250c6be9e">

The card get invisible when I apply fligging, I am on flutter 3.22 and building for web

**Comment by utpal-barman** [comment]
Hi @muhammed-amein,

Thanks for raising this issue!

This was fixed in version `u_credit_card: ^1.3.1`. If you are still using version 1.3.0, consider passing `CreditCardUi(width: <some value>, ...)`.

Let me know if this resolves your issue.
