### ISSUE TITLE
How to show whole number of card

### ISSUE THREAD

**Issue by desaivishal11** [utpal-barman/u-credit-card-flutter#27]
Thank you so much for providing nice widget. 

How do I show entire card number?

**Comment by utpal-barman** [comment]
> Thank you so much for providing nice widget. 
> 
> 
> 
> How do I show entire card number?

Thank you so much for trying out our package! I plan to add more flexibility and customization options in the future. The card number is currently hidden for security reasons, as it’s sensitive information, but I can enable visibility through a boolean setting in the next release. I hope this update will be useful to you!

**Comment by desaivishal11** [comment]
Thank you Utpal for quick reply. This would be nice add on because I want to show my user once they have the card, they can view the whole number. In meantime, I will display it somewhere on the page. Can you please give me some ETA for adding this?

**Comment by utpal-barman** [comment]
I’ll be working on this over the weekend, as this project is developed primarily during weekends. Hope I will have some time.

**Comment by utpal-barman** [comment]
Hi @desaivishal11,

A new version `u_credit_card: ^1.4.0` is available. See [pub.dev](https://pub.dev/packages/u_credit_card) page for more info. 

I've implemented the `shouldMaskCardNumber` feature, allowing you to unmask the card number by setting it to false. This option now defaults to `true` for security but can be adjusted based on your needs.

Thanks for your suggestion, and feel free to reach out if you have any further questions!

**Comment by desaivishal11** [comment]
Much appreciated. works fine now.
