### ISSUE TITLE
Issue with only last 4 digits in card number

### ISSUE THREAD

**Issue by burhankhanzada** [utpal-barman/u-credit-card-flutter#5]
When i provide only last 4 digits like this

```
CreditCardUi(
        cardHolderFullName: 'John Doe',
        cardNumber: '**** **** **** 1234',
        valid thru: '10/24',
 )
```

the result is this

![image](https://github.com/utpal-barman/u-credit-card-flutter/assets/18241005/9eb51875-5224-4318-a12a-47d30d9224ca)

**Comment by utpal-barman** [comment]
Hi @burhankhanzada, thanks for reporting the issue, we have fixed the issue in the PR #6
