### ISSUE TITLE
Remove Visa logo at bottom right coroner of the card

### ISSUE THREAD

**Issue by mantu-sahu** [utpal-barman/u-credit-card-flutter#9]
How to remove VISA logo.  This cannot be displayed for other card types.  cardProviderLogo does not override the VISA.

**Comment by mantu-sahu** [comment]
I noticed that you get the card type from the card number.  I do not have have full card number. I wanted to use the package to display the card in a view only mode. it is defaulting to visa.  i would rather no have that.  have the possibility to pass the card type then autodetecting it.

**Comment by utpal-barman** [comment]
Hi @mantu-sahu 

Thank you for bringing this issue to our attention, and I appreciate your patience. I'm glad to inform you that the issue has been fixed and addressed in the latest version of the package. You can now disable the card logo by using the `disableShowingCardLogo` property. This feature was introduced in `v1.0.6`.

To use `v1.0.6`, make sure you add this version:
```yaml
dependencies:
  u_credit_card: ^1.0.6
```

To utilize this feature, simply set `disableShowingCardLogo: true` in your `CreditCardUi(...)` widget.

If you encounter any further problems or have additional questions, please feel free to ask. Your feedback and engagement are valuable to us, and we're here to help.

Thank you for using our package and contributing to its improvement!

**Comment by mantu-sahu** [comment]
I suggest not to default to Visa card when you cannot determine the card brand.  That is just wrong. You would rather not show any logo. 

Secondly, instead of auto detecting it card brand from first digit of the card, optionally you should allow it to be passed in. 
In my case I do not have full card number.  Only last 4.  But I know what card scheme is.  There is no way I  can pass that information. 

The above feature of disableShowingCardLogo is good to have.
Thanks for your attention
